
--
-- args: <username> <password>

define _USERNAME = &1;
define _PASSWORD = &2 &&_USERNAME;


CREATE USER &&_USERNAME IDENTIFIED BY &&_PASSWORD
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
QUOTA UNLIMITED ON USERS
;

GRANT "CONNECT" TO &&_USERNAME ;
GRANT "RESOURCE" TO &&_USERNAME ;
ALTER USER &&_USERNAME DEFAULT ROLE "CONNECT","RESOURCE";


GRANT CREATE TABLE   TO &&_USERNAME ;
GRANT CREATE TYPE    TO &&_USERNAME ;
GRANT CREATE VIEW    TO &&_USERNAME ;
GRANT CREATE PROCEDURE TO &&_USERNAME ;
GRANT CREATE TRIGGER   TO &&_USERNAME ;
GRANT CREATE SYNONYM   TO &&_USERNAME ;
GRANT CREATE SEQUENCE  TO &&_USERNAME ;
GRANT CREATE MATERIALIZED VIEW TO &&_USERNAME ;





